name: Update apilink from loclx

on:
  push:
    branches:
      - main
    paths-ignore:
      - apilink
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-apilink:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Get tunnel info from LocalXpose
        id: get_tunnel
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.LOCX_API_TOKEN }}" https://api.localxpose.io/api/tunnels)
          echo "$response" > response.json
          URL=$(echo "$response" | jq -r '.tunnels[0].url // "offline"')
          echo "TUNNEL_URL=$URL" >> $GITHUB_ENV

      - name: Write apilink file
        run: |
          # Write without newline to avoid false no-change detection
          echo -n "$TUNNEL_URL" > apilink

      - name: Debug apilink content and git status
        run: |
          echo "apilink content:"
          cat apilink
          git status
          git diff apilink

      - name: Commit and push if changed
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add apilink
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Update apilink from LocalXpose [skip ci]"
            git push https://x-access-token:${GH_TOKEN}@github.com/NgbatzStudios/apikey.git HEAD:main
          fi
