name: Update apilink from loclx

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  update-apilink:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get tunnel info from LocalXpose
        id: get_tunnel
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.LOCX_API_TOKEN }}" https://api.localxpose.io/api/tunnels)
          echo "$response" > response.json
          
          # Parse the tunnel URL using jq
          URL=$(echo "$response" | jq -r '.tunnels[0].url // "offline"')
          echo "TUNNEL_URL=$URL" >> $GITHUB_ENV

      - name: Write apilink file
        run: echo "$TUNNEL_URL" > apilink

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add apilink
          git diff --quiet && git diff --staged --quiet || git commit -m "Update apilink from LocalXpose"
          git push
